/**
 * DRASSYAPP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taasekpaye@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CountryResponse model module.
 * @module model/CountryResponse
 * @version 1.0.0
 */
class CountryResponse {
    /**
     * Constructs a new <code>CountryResponse</code>.
     * @alias module:model/CountryResponse
     */
    constructor() { 
        
        CountryResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CountryResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CountryResponse} obj Optional instance to populate.
     * @return {module:model/CountryResponse} The populated <code>CountryResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CountryResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('call_code')) {
                obj['call_code'] = ApiClient.convertToType(data['call_code'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
CountryResponse.prototype['id'] = undefined;

/**
 * @member {String} code
 */
CountryResponse.prototype['code'] = undefined;

/**
 * @member {String} name
 */
CountryResponse.prototype['name'] = undefined;

/**
 * @member {String} call_code
 */
CountryResponse.prototype['call_code'] = undefined;






export default CountryResponse;

