/**
 * DRASSYBACKEND Server api doc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taasekpaye@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FinancialInfoUpdateModel model module.
 * @module model/FinancialInfoUpdateModel
 * @version 1.0.0
 */
class FinancialInfoUpdateModel {
    /**
     * Constructs a new <code>FinancialInfoUpdateModel</code>.
     * @alias module:model/FinancialInfoUpdateModel
     */
    constructor() { 
        
        FinancialInfoUpdateModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FinancialInfoUpdateModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FinancialInfoUpdateModel} obj Optional instance to populate.
     * @return {module:model/FinancialInfoUpdateModel} The populated <code>FinancialInfoUpdateModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FinancialInfoUpdateModel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('financial_stituation_id')) {
                obj['financial_stituation_id'] = ApiClient.convertToType(data['financial_stituation_id'], 'String');
            }
            if (data.hasOwnProperty('profession')) {
                obj['profession'] = ApiClient.convertToType(data['profession'], 'String');
            }
            if (data.hasOwnProperty('total_person_at_charge')) {
                obj['total_person_at_charge'] = ApiClient.convertToType(data['total_person_at_charge'], 'Number');
            }
            if (data.hasOwnProperty('balance')) {
                obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
            }
            if (data.hasOwnProperty('monthly_revenue')) {
                obj['monthly_revenue'] = ApiClient.convertToType(data['monthly_revenue'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
FinancialInfoUpdateModel.prototype['id'] = undefined;

/**
 * @member {String} financial_stituation_id
 */
FinancialInfoUpdateModel.prototype['financial_stituation_id'] = undefined;

/**
 * @member {String} profession
 */
FinancialInfoUpdateModel.prototype['profession'] = undefined;

/**
 * @member {Number} total_person_at_charge
 */
FinancialInfoUpdateModel.prototype['total_person_at_charge'] = undefined;

/**
 * @member {Number} balance
 */
FinancialInfoUpdateModel.prototype['balance'] = undefined;

/**
 * @member {Number} monthly_revenue
 */
FinancialInfoUpdateModel.prototype['monthly_revenue'] = undefined;






export default FinancialInfoUpdateModel;

