/**
 * DRASSYAPP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taasekpaye@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BusinessLine from './BusinessLine';
import FinancialSituationResponse from './FinancialSituationResponse';

/**
 * The FinancialInfoResponse model module.
 * @module model/FinancialInfoResponse
 * @version 1.0.0
 */
class FinancialInfoResponse {
    /**
     * Constructs a new <code>FinancialInfoResponse</code>.
     * @alias module:model/FinancialInfoResponse
     */
    constructor() { 
        
        FinancialInfoResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FinancialInfoResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FinancialInfoResponse} obj Optional instance to populate.
     * @return {module:model/FinancialInfoResponse} The populated <code>FinancialInfoResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FinancialInfoResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('balance')) {
                obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
            }
            if (data.hasOwnProperty('profession')) {
                obj['profession'] = ApiClient.convertToType(data['profession'], 'String');
            }
            if (data.hasOwnProperty('monthly_revenue')) {
                obj['monthly_revenue'] = ApiClient.convertToType(data['monthly_revenue'], 'String');
            }
            if (data.hasOwnProperty('matrimonial_status')) {
                obj['matrimonial_status'] = ApiClient.convertToType(data['matrimonial_status'], 'String');
            }
            if (data.hasOwnProperty('situation')) {
                obj['situation'] = FinancialSituationResponse.constructFromObject(data['situation']);
            }
            if (data.hasOwnProperty('businessLine')) {
                obj['businessLine'] = BusinessLine.constructFromObject(data['businessLine']);
            }
            if (data.hasOwnProperty('total_person_at_charge')) {
                obj['total_person_at_charge'] = ApiClient.convertToType(data['total_person_at_charge'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
FinancialInfoResponse.prototype['id'] = undefined;

/**
 * @member {Number} balance
 */
FinancialInfoResponse.prototype['balance'] = undefined;

/**
 * @member {String} profession
 */
FinancialInfoResponse.prototype['profession'] = undefined;

/**
 * @member {String} monthly_revenue
 */
FinancialInfoResponse.prototype['monthly_revenue'] = undefined;

/**
 * @member {String} matrimonial_status
 */
FinancialInfoResponse.prototype['matrimonial_status'] = undefined;

/**
 * @member {module:model/FinancialSituationResponse} situation
 */
FinancialInfoResponse.prototype['situation'] = undefined;

/**
 * @member {module:model/BusinessLine} businessLine
 */
FinancialInfoResponse.prototype['businessLine'] = undefined;

/**
 * @member {Number} total_person_at_charge
 */
FinancialInfoResponse.prototype['total_person_at_charge'] = undefined;






export default FinancialInfoResponse;

