/**
 * DRASSYAPP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taasekpaye@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FixedLoadModelRequest model module.
 * @module model/FixedLoadModelRequest
 * @version 1.0.0
 */
class FixedLoadModelRequest {
    /**
     * Constructs a new <code>FixedLoadModelRequest</code>.
     * @alias module:model/FixedLoadModelRequest
     */
    constructor() { 
        
        FixedLoadModelRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FixedLoadModelRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FixedLoadModelRequest} obj Optional instance to populate.
     * @return {module:model/FixedLoadModelRequest} The populated <code>FixedLoadModelRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FixedLoadModelRequest();

            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('type_transactionId')) {
                obj['type_transactionId'] = ApiClient.convertToType(data['type_transactionId'], 'String');
            }
            if (data.hasOwnProperty('dateLoop')) {
                obj['dateLoop'] = ApiClient.convertToType(data['dateLoop'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} userId
 */
FixedLoadModelRequest.prototype['userId'] = undefined;

/**
 * @member {Number} amount
 */
FixedLoadModelRequest.prototype['amount'] = undefined;

/**
 * @member {String} type_transactionId
 */
FixedLoadModelRequest.prototype['type_transactionId'] = undefined;

/**
 * @member {Number} dateLoop
 */
FixedLoadModelRequest.prototype['dateLoop'] = undefined;






export default FixedLoadModelRequest;

