/**
 * DRASSYAPP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taasekpaye@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InvestOptionResponse model module.
 * @module model/InvestOptionResponse
 * @version 1.0.0
 */
class InvestOptionResponse {
    /**
     * Constructs a new <code>InvestOptionResponse</code>.
     * @alias module:model/InvestOptionResponse
     */
    constructor() { 
        
        InvestOptionResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InvestOptionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InvestOptionResponse} obj Optional instance to populate.
     * @return {module:model/InvestOptionResponse} The populated <code>InvestOptionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvestOptionResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('isAvailable')) {
                obj['isAvailable'] = ApiClient.convertToType(data['isAvailable'], 'Boolean');
            }
            if (data.hasOwnProperty('asset_name')) {
                obj['asset_name'] = ApiClient.convertToType(data['asset_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
InvestOptionResponse.prototype['id'] = undefined;

/**
 * @member {String} name
 */
InvestOptionResponse.prototype['name'] = undefined;

/**
 * @member {Boolean} isAvailable
 */
InvestOptionResponse.prototype['isAvailable'] = undefined;

/**
 * @member {String} asset_name
 */
InvestOptionResponse.prototype['asset_name'] = undefined;






export default InvestOptionResponse;

