/**
 * DRASSYBACKEND Server api doc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taasekpaye@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InvestSubscribeModel model module.
 * @module model/InvestSubscribeModel
 * @version 1.0.0
 */
class InvestSubscribeModel {
    /**
     * Constructs a new <code>InvestSubscribeModel</code>.
     * @alias module:model/InvestSubscribeModel
     */
    constructor() { 
        
        InvestSubscribeModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InvestSubscribeModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InvestSubscribeModel} obj Optional instance to populate.
     * @return {module:model/InvestSubscribeModel} The populated <code>InvestSubscribeModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvestSubscribeModel();

            if (data.hasOwnProperty('investment_id')) {
                obj['investment_id'] = ApiClient.convertToType(data['investment_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} investment_id
 */
InvestSubscribeModel.prototype['investment_id'] = undefined;






export default InvestSubscribeModel;

