/**
 * DRASSYAPP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taasekpaye@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PhoneVerificationModel model module.
 * @module model/PhoneVerificationModel
 * @version 1.0.0
 */
class PhoneVerificationModel {
    /**
     * Constructs a new <code>PhoneVerificationModel</code>.
     * @alias module:model/PhoneVerificationModel
     */
    constructor() { 
        
        PhoneVerificationModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PhoneVerificationModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PhoneVerificationModel} obj Optional instance to populate.
     * @return {module:model/PhoneVerificationModel} The populated <code>PhoneVerificationModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PhoneVerificationModel();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('phone_id')) {
                obj['phone_id'] = ApiClient.convertToType(data['phone_id'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
PhoneVerificationModel.prototype['name'] = undefined;

/**
 * @member {String} phone_id
 */
PhoneVerificationModel.prototype['phone_id'] = undefined;

/**
 * @member {String} version
 */
PhoneVerificationModel.prototype['version'] = undefined;






export default PhoneVerificationModel;

