/**
 * DRASSYAPP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taasekpaye@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TransactionType from './TransactionType';

/**
 * The TransactionResponse model module.
 * @module model/TransactionResponse
 * @version 1.0.0
 */
class TransactionResponse {
    /**
     * Constructs a new <code>TransactionResponse</code>.
     * @alias module:model/TransactionResponse
     */
    constructor() { 
        
        TransactionResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransactionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionResponse} obj Optional instance to populate.
     * @return {module:model/TransactionResponse} The populated <code>TransactionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Number');
            }
            if (data.hasOwnProperty('type_transaction')) {
                obj['type_transaction'] = TransactionType.constructFromObject(data['type_transaction']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
TransactionResponse.prototype['id'] = undefined;

/**
 * @member {String} note
 */
TransactionResponse.prototype['note'] = undefined;

/**
 * @member {Number} amount
 */
TransactionResponse.prototype['amount'] = undefined;

/**
 * @member {Number} created_at
 */
TransactionResponse.prototype['created_at'] = undefined;

/**
 * @member {module:model/TransactionType} type_transaction
 */
TransactionResponse.prototype['type_transaction'] = undefined;






export default TransactionResponse;

