/**
 * DRASSYBACKEND Server api doc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taasekpaye@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CountryResponse from './CountryResponse';

/**
 * The UserInfoResponse model module.
 * @module model/UserInfoResponse
 * @version 1.0.0
 */
class UserInfoResponse {
    /**
     * Constructs a new <code>UserInfoResponse</code>.
     * @alias module:model/UserInfoResponse
     */
    constructor() { 
        
        UserInfoResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserInfoResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserInfoResponse} obj Optional instance to populate.
     * @return {module:model/UserInfoResponse} The populated <code>UserInfoResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserInfoResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('full_name')) {
                obj['full_name'] = ApiClient.convertToType(data['full_name'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('sex')) {
                obj['sex'] = ApiClient.convertToType(data['sex'], 'String');
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
            }
            if (data.hasOwnProperty('Country')) {
                obj['Country'] = CountryResponse.constructFromObject(data['Country']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
UserInfoResponse.prototype['id'] = undefined;

/**
 * @member {String} full_name
 */
UserInfoResponse.prototype['full_name'] = undefined;

/**
 * @member {String} email
 */
UserInfoResponse.prototype['email'] = undefined;

/**
 * @member {String} phone
 */
UserInfoResponse.prototype['phone'] = undefined;

/**
 * @member {String} sex
 */
UserInfoResponse.prototype['sex'] = undefined;

/**
 * @member {String} scope
 */
UserInfoResponse.prototype['scope'] = undefined;

/**
 * @member {module:model/CountryResponse} Country
 */
UserInfoResponse.prototype['Country'] = undefined;






export default UserInfoResponse;

