/**
 * DRASSYBACKEND Server api doc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taasekpaye@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CountryResponse from '../model/CountryResponse';
import CreateCountryModel from '../model/CreateCountryModel';

/**
* Country service.
* @module api/CountryApi
* @version 1.0.0
*/
export default class CountryApi {

    /**
    * Constructs a new CountryApi. 
    * @alias module:api/CountryApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the postCountryCreate operation.
     * @callback module:api/CountryApi~postCountryCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CountryResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new country
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateCountryModel} opts.body 
     * @param {module:api/CountryApi~postCountryCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CountryResponse}
     */
    postCountryCreate(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = CountryResponse;
      return this.apiClient.callApi(
        '/country/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
