/**
 * DRASSYAPP
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taasekpaye@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import FixedLoadModelRequest from '../model/FixedLoadModelRequest';
import FixedLoadResponse from '../model/FixedLoadResponse';

/**
* FixedLoad service.
* @module api/FixedLoadApi
* @version 1.0.0
*/
export default class FixedLoadApi {

    /**
    * Constructs a new FixedLoadApi. 
    * @alias module:api/FixedLoadApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the deleteFixedloadId operation.
     * @callback module:api/FixedLoadApi~deleteFixedloadIdCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete load
     * Return User info
     * @param {String} id 
     * @param {module:api/FixedLoadApi~deleteFixedloadIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    deleteFixedloadId(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteFixedloadId");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/fixedload/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getFixedload operation.
     * @callback module:api/FixedLoadApi~getFixedloadCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/FixedLoadResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * User fixed Load list
     * List user fixed Load
     * @param {module:api/FixedLoadApi~getFixedloadCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/FixedLoadResponse>}
     */
    getFixedload(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [FixedLoadResponse];
      return this.apiClient.callApi(
        '/fixedload', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postFixedloadCreate operation.
     * @callback module:api/FixedLoadApi~postFixedloadCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/FixedLoadResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a fixed load
     * Return fixed laod
     * @param {Object} opts Optional parameters
     * @param {module:model/FixedLoadModelRequest} opts.body 
     * @param {module:api/FixedLoadApi~postFixedloadCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/FixedLoadResponse}
     */
    postFixedloadCreate(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = FixedLoadResponse;
      return this.apiClient.callApi(
        '/fixedload/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
