/**
 * DRASSYBACKEND Server api doc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taasekpaye@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import InvestOptionResponse from '../model/InvestOptionResponse';
import InvestSubscribeModel from '../model/InvestSubscribeModel';
import InvestSubscribeResponse from '../model/InvestSubscribeResponse';

/**
* Invest service.
* @module api/InvestApi
* @version 1.0.0
*/
export default class InvestApi {

    /**
    * Constructs a new InvestApi. 
    * @alias module:api/InvestApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getInvestList operation.
     * @callback module:api/InvestApi~getInvestListCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/InvestOptionResponse>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     *  list invest option list
     * Return invest option list
     * @param {module:api/InvestApi~getInvestListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/InvestOptionResponse>}
     */
    getInvestList(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [InvestOptionResponse];
      return this.apiClient.callApi(
        '/invest/list', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the postInvestSubscribe operation.
     * @callback module:api/InvestApi~postInvestSubscribeCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InvestSubscribeResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Subscribe to invest
     * Return fixed laod
     * @param {Object} opts Optional parameters
     * @param {module:model/InvestSubscribeModel} opts.body 
     * @param {module:api/InvestApi~postInvestSubscribeCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InvestSubscribeResponse}
     */
    postInvestSubscribe(opts, callback) {
      opts = opts || {};
      let postBody = opts['body'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = InvestSubscribeResponse;
      return this.apiClient.callApi(
        '/invest/subscribe', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
