/**
 * DRASSYBACKEND Server api doc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taasekpaye@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DrassybackendServerApiDoc);
  }
}(this, function(expect, DrassybackendServerApiDoc) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DrassybackendServerApiDoc.NewFinancialInfoModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NewFinancialInfoModel', function() {
    it('should create an instance of NewFinancialInfoModel', function() {
      // uncomment below and update the code to test NewFinancialInfoModel
      //var instance = new DrassybackendServerApiDoc.NewFinancialInfoModel();
      //expect(instance).to.be.a(DrassybackendServerApiDoc.NewFinancialInfoModel);
    });

    it('should have the property financialStituationId (base name: "financial_stituation_id")', function() {
      // uncomment below and update the code to test the property financialStituationId
      //var instance = new DrassybackendServerApiDoc.NewFinancialInfoModel();
      //expect(instance).to.be();
    });

    it('should have the property profession (base name: "profession")', function() {
      // uncomment below and update the code to test the property profession
      //var instance = new DrassybackendServerApiDoc.NewFinancialInfoModel();
      //expect(instance).to.be();
    });

    it('should have the property businessLineId (base name: "business_lineId")', function() {
      // uncomment below and update the code to test the property businessLineId
      //var instance = new DrassybackendServerApiDoc.NewFinancialInfoModel();
      //expect(instance).to.be();
    });

    it('should have the property totalPersonAtCharge (base name: "total_person_at_charge")', function() {
      // uncomment below and update the code to test the property totalPersonAtCharge
      //var instance = new DrassybackendServerApiDoc.NewFinancialInfoModel();
      //expect(instance).to.be();
    });

    it('should have the property balance (base name: "balance")', function() {
      // uncomment below and update the code to test the property balance
      //var instance = new DrassybackendServerApiDoc.NewFinancialInfoModel();
      //expect(instance).to.be();
    });

    it('should have the property monthlyRevenue (base name: "monthly_revenue")', function() {
      // uncomment below and update the code to test the property monthlyRevenue
      //var instance = new DrassybackendServerApiDoc.NewFinancialInfoModel();
      //expect(instance).to.be();
    });

    it('should have the property matrimonialStatus (base name: "matrimonial_status")', function() {
      // uncomment below and update the code to test the property matrimonialStatus
      //var instance = new DrassybackendServerApiDoc.NewFinancialInfoModel();
      //expect(instance).to.be();
    });

  });

}));
