/**
 * DRASSYBACKEND Server api doc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taasekpaye@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DrassybackendServerApiDoc);
  }
}(this, function(expect, DrassybackendServerApiDoc) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DrassybackendServerApiDoc.AuthApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthApi', function() {
    describe('getAuthWhoami', function() {
      it('should call getAuthWhoami successfully', function(done) {
        //uncomment below and update the code to test getAuthWhoami
        //instance.getAuthWhoami(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postAuthChangepassword', function() {
      it('should call postAuthChangepassword successfully', function(done) {
        //uncomment below and update the code to test postAuthChangepassword
        //instance.postAuthChangepassword(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postAuthCreateCredential', function() {
      it('should call postAuthCreateCredential successfully', function(done) {
        //uncomment below and update the code to test postAuthCreateCredential
        //instance.postAuthCreateCredential(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postAuthLogin', function() {
      it('should call postAuthLogin successfully', function(done) {
        //uncomment below and update the code to test postAuthLogin
        //instance.postAuthLogin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postAuthRegister', function() {
      it('should call postAuthRegister successfully', function(done) {
        //uncomment below and update the code to test postAuthRegister
        //instance.postAuthRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postAuthReinitpassword', function() {
      it('should call postAuthReinitpassword successfully', function(done) {
        //uncomment below and update the code to test postAuthReinitpassword
        //instance.postAuthReinitpassword(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postAuthRenew', function() {
      it('should call postAuthRenew successfully', function(done) {
        //uncomment below and update the code to test postAuthRenew
        //instance.postAuthRenew(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postAuthRequestpin', function() {
      it('should call postAuthRequestpin successfully', function(done) {
        //uncomment below and update the code to test postAuthRequestpin
        //instance.postAuthRequestpin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postAuthVerifypin', function() {
      it('should call postAuthVerifypin successfully', function(done) {
        //uncomment below and update the code to test postAuthVerifypin
        //instance.postAuthVerifypin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
