/**
 * DRASSYBACKEND Server api doc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taasekpaye@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DrassybackendServerApiDoc);
  }
}(this, function(expect, DrassybackendServerApiDoc) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DrassybackendServerApiDoc.ParamsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ParamsApi', function() {
    describe('deleteParamsProfessionDeleteId', function() {
      it('should call deleteParamsProfessionDeleteId successfully', function(done) {
        //uncomment below and update the code to test deleteParamsProfessionDeleteId
        //instance.deleteParamsProfessionDeleteId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteParamsRevenueDeleteId', function() {
      it('should call deleteParamsRevenueDeleteId successfully', function(done) {
        //uncomment below and update the code to test deleteParamsRevenueDeleteId
        //instance.deleteParamsRevenueDeleteId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteParamsWagesDeleteId', function() {
      it('should call deleteParamsWagesDeleteId successfully', function(done) {
        //uncomment below and update the code to test deleteParamsWagesDeleteId
        //instance.deleteParamsWagesDeleteId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParamsBusinesslineList', function() {
      it('should call getParamsBusinesslineList successfully', function(done) {
        //uncomment below and update the code to test getParamsBusinesslineList
        //instance.getParamsBusinesslineList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParamsFinancialsituation', function() {
      it('should call getParamsFinancialsituation successfully', function(done) {
        //uncomment below and update the code to test getParamsFinancialsituation
        //instance.getParamsFinancialsituation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParamsListcountries', function() {
      it('should call getParamsListcountries successfully', function(done) {
        //uncomment below and update the code to test getParamsListcountries
        //instance.getParamsListcountries(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParamsMatrimonials', function() {
      it('should call getParamsMatrimonials successfully', function(done) {
        //uncomment below and update the code to test getParamsMatrimonials
        //instance.getParamsMatrimonials(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParamsOperation', function() {
      it('should call getParamsOperation successfully', function(done) {
        //uncomment below and update the code to test getParamsOperation
        //instance.getParamsOperation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParamsProfessionList', function() {
      it('should call getParamsProfessionList successfully', function(done) {
        //uncomment below and update the code to test getParamsProfessionList
        //instance.getParamsProfessionList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParamsRevenueList', function() {
      it('should call getParamsRevenueList successfully', function(done) {
        //uncomment below and update the code to test getParamsRevenueList
        //instance.getParamsRevenueList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParamsTransactiontype', function() {
      it('should call getParamsTransactiontype successfully', function(done) {
        //uncomment below and update the code to test getParamsTransactiontype
        //instance.getParamsTransactiontype(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getParamsWagesList', function() {
      it('should call getParamsWagesList successfully', function(done) {
        //uncomment below and update the code to test getParamsWagesList
        //instance.getParamsWagesList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postParamsBusinesslineNew', function() {
      it('should call postParamsBusinesslineNew successfully', function(done) {
        //uncomment below and update the code to test postParamsBusinesslineNew
        //instance.postParamsBusinesslineNew(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postParamsProfessionNew', function() {
      it('should call postParamsProfessionNew successfully', function(done) {
        //uncomment below and update the code to test postParamsProfessionNew
        //instance.postParamsProfessionNew(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postParamsRevenueNew', function() {
      it('should call postParamsRevenueNew successfully', function(done) {
        //uncomment below and update the code to test postParamsRevenueNew
        //instance.postParamsRevenueNew(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postParamsWagesNew', function() {
      it('should call postParamsWagesNew successfully', function(done) {
        //uncomment below and update the code to test postParamsWagesNew
        //instance.postParamsWagesNew(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
