/**
 * DRASSYBACKEND Server api doc
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: taasekpaye@outlook.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DrassybackendServerApiDoc);
  }
}(this, function(expect, DrassybackendServerApiDoc) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DrassybackendServerApiDoc.TransactionApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TransactionApi', function() {
    describe('deleteTransactionDeleteId', function() {
      it('should call deleteTransactionDeleteId successfully', function(done) {
        //uncomment below and update the code to test deleteTransactionDeleteId
        //instance.deleteTransactionDeleteId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTransactionDate', function() {
      it('should call getTransactionDate successfully', function(done) {
        //uncomment below and update the code to test getTransactionDate
        //instance.getTransactionDate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTransactionPeriod', function() {
      it('should call getTransactionPeriod successfully', function(done) {
        //uncomment below and update the code to test getTransactionPeriod
        //instance.getTransactionPeriod(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTransactionSearch', function() {
      it('should call getTransactionSearch successfully', function(done) {
        //uncomment below and update the code to test getTransactionSearch
        //instance.getTransactionSearch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postTransactionCreate', function() {
      it('should call postTransactionCreate successfully', function(done) {
        //uncomment below and update the code to test postTransactionCreate
        //instance.postTransactionCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putTransactionUpdate', function() {
      it('should call putTransactionUpdate successfully', function(done) {
        //uncomment below and update the code to test putTransactionUpdate
        //instance.putTransactionUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
